[[redirects]]
  from = "/sunnuntai"
  to = "/sunnuntai.html"
  status = 200

[[redirects]]
  from = "/lapset"
  to = "/lapset.html"
  status = 200

[[redirects]]
  from = "/evankeliointi"
  to = "/evankeliointi.html"
  status = 200

[[redirects]]
  from = "/raamattukoulu"
  to = "/raamattukoulu.html"
  status = 200

[[redirects]]
  from = "/tapahtumat"
  to = "/tapahtumat.html"
  status = 200

[[redirects]]
  from = "/yhteys"
  to = "/yhteys.html"
  status = 200

[[redirects]]
  from = "/english"
  to = "/english.html"
  status = 200
